name: Apptio Targetprocess Organization Workflow
run-name: apptp-workflow

on:
  push:
    branches:
      - $default-branch
      - feature/us*
  pull_request:
    types:
      - opened
    branches:
      - $default-branch

jobs:
  test:
    strategy:
      matrix:
        project: [ CHANGE_ME ]
    uses: 'TargetProcess/gitlab-migration-test/.github/workflows/test-workflow.yml@feature/us817038-workflow-template'
    with:
      project-name: ${{ matrix.project }}
      ec-lint-enabled: true
