name: Apptio Targetprocess Organization Workflow
run-name: apptp-workflow

on:
  push:
    branches:
      - $default-branch
      - feature/us*
  pull_request:
    types:
      - opened
    branches:
      - $default-branch

jobs:
  test:
    strategy:
      matrix:
        project: [ CHANGE_ME ]
    uses: 'TargetProcess/gitlab-migration-test/.github/workflows/test-workflow.yml@0d7c8138b16ff13f563f5c55121b7db81564ed02'
    with:
      project-name: ${{ matrix.project }}
      ec-lint-enabled: true
